title: Links Repository
description: Collection of Awesome Websites
author:
  name: Arif Budiman
  email: mailbox@arifbudiman.web.id
  
remote_theme: jekyll/minima@d4d779a

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
#   Minima skin selection. Available skins are:
#     * classic            Default, light color scheme.
#     * dark               Dark variant of the classic skin.
#     * auto               Adaptive skin based on the classic and dark skins.
#     * solarized-light    Light variant of solarized color scheme.
#     * solarized-dark     Dark variant of solarized color scheme.
#     * solarized          Adaptive skin for solarized color scheme skins.
  skin: auto

nav_pages:
  - about.md

#   Set to `true` to show excerpts on the homepage.
show_excerpts: true
#
#   Minima date format.
#     The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
#     Refer to https://shopify.github.io/liquid/filters/date/ for valid values
#   date_format: "%b-%d-%Y"

social_links:
  - title: Minima Theme repository at GitHub
    icon: github
    url: "https://github.com/jekyll/minima"
  - title: Jekyll at X (formerly Twitter)
    icon: x-twitter
    url: "https://x.com/jekyllrb"
